# Gems
gems: [jekyll-paginate]

# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            '호군의 개발살이'
tagline:          'blog'
description:      '안드로이드 개발 경험을 공유합니다'
url:              http://dhna.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Dongho Na
  url:            https://plus.google.com/u/1/106771491007235618927

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
#  - icon:         twitter
#    url:          https://twitter.com/iancamporez
#    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/dhna
    desc:         Fork me on github

#  - icon:         googleplus-alt
#    url:          https://google.com/+IanCamporezBrunelli
#    desc:         Add me on google+

  - icon:         feed
    url:          http://dhna.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Dongho Na
  url:            http://dhna.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
